// Lightweight emoji shortcode dataset + fuzzy lookup for the `:shortcode` autocomplete.
// Curated to cover the emoji people actually reach for in a messaging app, without
// pulling in a multi-megabyte dependency.

export interface Emoji {
  /** The emoji character. */
  char: string;
  /** Primary shortcode, lowercase, no surrounding colons (e.g. "heart"). */
  name: string;
  /** Extra search terms / aliases. */
  keywords?: string[];
}

export const EMOJIS: Emoji[] = [
  // Smileys & emotion
  { char: "😀", name: "grinning", keywords: ["smile", "happy"] },
  { char: "😃", name: "smiley", keywords: ["happy", "joy"] },
  { char: "😄", name: "smile", keywords: ["happy", "laugh"] },
  { char: "😁", name: "grin", keywords: ["happy"] },
  { char: "😆", name: "laughing", keywords: ["lol", "haha", "satisfied"] },
  { char: "😅", name: "sweat_smile", keywords: ["relief", "nervous"] },
  { char: "🤣", name: "rofl", keywords: ["lol", "rolling", "laugh"] },
  { char: "😂", name: "joy", keywords: ["lol", "laugh", "tears", "cry"] },
  { char: "🙂", name: "slight_smile", keywords: ["smile"] },
  { char: "🙃", name: "upside_down", keywords: ["silly", "irony"] },
  { char: "😉", name: "wink", keywords: ["flirt"] },
  { char: "😊", name: "blush", keywords: ["smile", "happy", "shy"] },
  { char: "😇", name: "innocent", keywords: ["angel", "halo"] },
  { char: "🥰", name: "smiling_face_with_hearts", keywords: ["love", "adore"] },
  { char: "😍", name: "heart_eyes", keywords: ["love", "crush"] },
  { char: "🤩", name: "star_struck", keywords: ["wow", "amazed"] },
  { char: "😘", name: "kissing_heart", keywords: ["kiss", "love"] },
  { char: "😗", name: "kissing", keywords: ["kiss"] },
  { char: "😚", name: "kissing_closed_eyes", keywords: ["kiss"] },
  { char: "😙", name: "kissing_smiling_eyes", keywords: ["kiss"] },
  { char: "😋", name: "yum", keywords: ["tasty", "delicious", "tongue"] },
  { char: "😛", name: "stuck_out_tongue", keywords: ["tongue", "silly"] },
  { char: "😜", name: "stuck_out_tongue_winking_eye", keywords: ["tongue", "wink"] },
  { char: "🤪", name: "zany", keywords: ["crazy", "silly", "goofy"] },
  { char: "😝", name: "stuck_out_tongue_closed_eyes", keywords: ["tongue"] },
  { char: "🤑", name: "money_mouth", keywords: ["money", "rich"] },
  { char: "🤗", name: "hugs", keywords: ["hug", "embrace"] },
  { char: "🤭", name: "hand_over_mouth", keywords: ["oops", "giggle"] },
  { char: "🤫", name: "shushing", keywords: ["quiet", "shh", "secret"] },
  { char: "🤔", name: "thinking", keywords: ["hmm", "consider"] },
  { char: "🤐", name: "zipper_mouth", keywords: ["secret", "quiet"] },
  { char: "🤨", name: "raised_eyebrow", keywords: ["skeptical", "suspicious"] },
  { char: "😐", name: "neutral", keywords: ["meh", "blank"] },
  { char: "😑", name: "expressionless", keywords: ["blank"] },
  { char: "😶", name: "no_mouth", keywords: ["silent", "speechless"] },
  { char: "😏", name: "smirk", keywords: ["smug", "flirt"] },
  { char: "😒", name: "unamused", keywords: ["meh", "annoyed"] },
  { char: "🙄", name: "roll_eyes", keywords: ["annoyed", "whatever"] },
  { char: "😬", name: "grimacing", keywords: ["awkward", "eek"] },
  { char: "🤥", name: "lying", keywords: ["pinocchio", "liar"] },
  { char: "😌", name: "relieved", keywords: ["calm", "content"] },
  { char: "😔", name: "pensive", keywords: ["sad", "sigh"] },
  { char: "😪", name: "sleepy", keywords: ["tired"] },
  { char: "🤤", name: "drooling", keywords: ["drool", "hungry"] },
  { char: "😴", name: "sleeping", keywords: ["sleep", "zzz", "tired"] },
  { char: "😷", name: "mask", keywords: ["sick", "covid"] },
  { char: "🤒", name: "thermometer_face", keywords: ["sick", "ill"] },
  { char: "🤕", name: "head_bandage", keywords: ["hurt", "injured"] },
  { char: "🤢", name: "nauseated", keywords: ["sick", "gross"] },
  { char: "🤮", name: "vomiting", keywords: ["sick", "puke"] },
  { char: "🤧", name: "sneezing", keywords: ["sick", "achoo"] },
  { char: "🥵", name: "hot_face", keywords: ["hot", "heat", "sweat"] },
  { char: "🥶", name: "cold_face", keywords: ["cold", "freezing"] },
  { char: "🥴", name: "woozy", keywords: ["drunk", "dizzy"] },
  { char: "😵", name: "dizzy_face", keywords: ["dead", "knocked out"] },
  { char: "🤯", name: "exploding_head", keywords: ["mind blown", "shock"] },
  { char: "🤠", name: "cowboy", keywords: ["yeehaw"] },
  { char: "🥳", name: "partying_face", keywords: ["party", "celebrate", "birthday"] },
  { char: "😎", name: "sunglasses", keywords: ["cool", "deal with it"] },
  { char: "🤓", name: "nerd", keywords: ["geek", "smart"] },
  { char: "🧐", name: "monocle", keywords: ["inspect", "fancy"] },
  { char: "😕", name: "confused", keywords: ["unsure"] },
  { char: "😟", name: "worried", keywords: ["concerned"] },
  { char: "🙁", name: "slight_frown", keywords: ["sad"] },
  { char: "☹️", name: "frowning", keywords: ["sad"] },
  { char: "😮", name: "open_mouth", keywords: ["wow", "surprised"] },
  { char: "😯", name: "hushed", keywords: ["surprised"] },
  { char: "😲", name: "astonished", keywords: ["shocked", "wow"] },
  { char: "😳", name: "flushed", keywords: ["embarrassed", "blush"] },
  { char: "🥺", name: "pleading", keywords: ["puppy eyes", "please", "begging"] },
  { char: "😦", name: "frowning_open", keywords: ["sad"] },
  { char: "😧", name: "anguished", keywords: ["shocked"] },
  { char: "😨", name: "fearful", keywords: ["scared"] },
  { char: "😰", name: "cold_sweat", keywords: ["nervous", "anxious"] },
  { char: "😥", name: "disappointed_relieved", keywords: ["sad", "phew"] },
  { char: "😢", name: "cry", keywords: ["sad", "tear"] },
  { char: "😭", name: "sob", keywords: ["cry", "sad", "bawling"] },
  { char: "😱", name: "scream", keywords: ["shocked", "fear", "omg"] },
  { char: "😖", name: "confounded", keywords: ["frustrated"] },
  { char: "😣", name: "persevere", keywords: ["struggle"] },
  { char: "😞", name: "disappointed", keywords: ["sad"] },
  { char: "😓", name: "sweat", keywords: ["nervous"] },
  { char: "😩", name: "weary", keywords: ["tired", "ugh"] },
  { char: "😫", name: "tired_face", keywords: ["exhausted", "ugh"] },
  { char: "🥱", name: "yawning", keywords: ["bored", "tired"] },
  { char: "😤", name: "triumph", keywords: ["proud", "huff"] },
  { char: "😡", name: "rage", keywords: ["angry", "mad"] },
  { char: "😠", name: "angry", keywords: ["mad"] },
  { char: "🤬", name: "cursing", keywords: ["swearing", "angry"] },
  { char: "😈", name: "smiling_imp", keywords: ["devil", "evil"] },
  { char: "👿", name: "imp", keywords: ["devil", "angry"] },
  { char: "💀", name: "skull", keywords: ["dead", "death", "im dead"] },
  { char: "💩", name: "poop", keywords: ["poo", "crap"] },
  { char: "🤡", name: "clown", keywords: ["joke", "fool"] },
  { char: "👹", name: "ogre", keywords: ["monster"] },
  { char: "👻", name: "ghost", keywords: ["boo", "halloween"] },
  { char: "👽", name: "alien", keywords: ["ufo", "space"] },
  { char: "🤖", name: "robot", keywords: ["bot", "ai"] },
  { char: "😺", name: "smiley_cat", keywords: ["cat"] },
  { char: "😻", name: "heart_eyes_cat", keywords: ["cat", "love"] },

  // Gestures & people
  { char: "👋", name: "wave", keywords: ["hello", "hi", "bye"] },
  { char: "🤚", name: "raised_back_of_hand", keywords: ["stop"] },
  { char: "✋", name: "raised_hand", keywords: ["high five", "stop"] },
  { char: "🖐️", name: "hand_splayed", keywords: ["five"] },
  { char: "🖖", name: "vulcan", keywords: ["spock", "live long"] },
  { char: "👌", name: "ok_hand", keywords: ["okay", "perfect"] },
  { char: "🤌", name: "pinched_fingers", keywords: ["italian", "chefs kiss"] },
  { char: "🤏", name: "pinch", keywords: ["small", "tiny"] },
  { char: "✌️", name: "v", keywords: ["peace", "victory"] },
  { char: "🤞", name: "fingers_crossed", keywords: ["luck", "hopeful"] },
  { char: "🤟", name: "love_you_gesture", keywords: ["love"] },
  { char: "🤘", name: "metal", keywords: ["rock", "horns"] },
  { char: "🤙", name: "call_me", keywords: ["shaka", "hang loose"] },
  { char: "👈", name: "point_left", keywords: ["left"] },
  { char: "👉", name: "point_right", keywords: ["right"] },
  { char: "👆", name: "point_up_2", keywords: ["up"] },
  { char: "👇", name: "point_down", keywords: ["down"] },
  { char: "☝️", name: "point_up", keywords: ["up", "one"] },
  { char: "👍", name: "thumbsup", keywords: ["+1", "like", "yes", "thumbs up", "approve"] },
  { char: "👎", name: "thumbsdown", keywords: ["-1", "dislike", "no", "thumbs down"] },
  { char: "✊", name: "fist", keywords: ["power", "punch"] },
  { char: "👊", name: "facepunch", keywords: ["fist bump", "bro"] },
  { char: "🤛", name: "left_fist", keywords: ["fist bump"] },
  { char: "🤜", name: "right_fist", keywords: ["fist bump"] },
  { char: "👏", name: "clap", keywords: ["applause", "bravo"] },
  { char: "🙌", name: "raised_hands", keywords: ["praise", "hooray", "celebrate"] },
  { char: "👐", name: "open_hands", keywords: ["hug"] },
  { char: "🤲", name: "palms_up", keywords: ["pray", "cupped"] },
  { char: "🙏", name: "pray", keywords: ["please", "thanks", "thank you", "namaste", "high five"] },
  { char: "🤝", name: "handshake", keywords: ["deal", "agreement"] },
  { char: "💪", name: "muscle", keywords: ["strong", "flex", "gym"] },
  { char: "🫶", name: "heart_hands", keywords: ["love"] },
  { char: "🫰", name: "finger_heart", keywords: ["love", "money"] },

  // Hearts & symbols
  { char: "❤️", name: "heart", keywords: ["love", "red heart"] },
  { char: "🧡", name: "orange_heart", keywords: ["love"] },
  { char: "💛", name: "yellow_heart", keywords: ["love"] },
  { char: "💚", name: "green_heart", keywords: ["love"] },
  { char: "💙", name: "blue_heart", keywords: ["love"] },
  { char: "💜", name: "purple_heart", keywords: ["love"] },
  { char: "🖤", name: "black_heart", keywords: ["love"] },
  { char: "🤍", name: "white_heart", keywords: ["love"] },
  { char: "🤎", name: "brown_heart", keywords: ["love"] },
  { char: "💕", name: "two_hearts", keywords: ["love"] },
  { char: "💞", name: "revolving_hearts", keywords: ["love"] },
  { char: "💓", name: "heartbeat", keywords: ["love", "pulse"] },
  { char: "💗", name: "heartpulse", keywords: ["love", "growing"] },
  { char: "💖", name: "sparkling_heart", keywords: ["love"] },
  { char: "💘", name: "cupid", keywords: ["love", "arrow"] },
  { char: "💝", name: "gift_heart", keywords: ["love"] },
  { char: "💔", name: "broken_heart", keywords: ["sad", "heartbreak"] },
  { char: "❣️", name: "heart_exclamation", keywords: ["love"] },
  { char: "💯", name: "100", keywords: ["hundred", "perfect", "score"] },
  { char: "💢", name: "anger", keywords: ["mad"] },
  { char: "💥", name: "boom", keywords: ["explosion", "collision"] },
  { char: "💫", name: "dizzy", keywords: ["stars"] },
  { char: "💦", name: "sweat_drops", keywords: ["water", "splash"] },
  { char: "💨", name: "dash", keywords: ["wind", "fast"] },
  { char: "🕳️", name: "hole", keywords: [] },
  { char: "💬", name: "speech_balloon", keywords: ["comment", "chat"] },
  { char: "💭", name: "thought_balloon", keywords: ["thinking"] },
  { char: "💤", name: "zzz", keywords: ["sleep", "tired"] },
  { char: "⭐", name: "star", keywords: ["favorite"] },
  { char: "🌟", name: "star2", keywords: ["glowing", "sparkle"] },
  { char: "✨", name: "sparkles", keywords: ["shiny", "magic", "clean"] },
  { char: "⚡", name: "zap", keywords: ["lightning", "fast", "thunder"] },
  { char: "🔥", name: "fire", keywords: ["lit", "hot", "flame"] },
  { char: "🎉", name: "tada", keywords: ["party", "celebrate", "congrats"] },
  { char: "🎊", name: "confetti_ball", keywords: ["party", "celebrate"] },
  { char: "🎈", name: "balloon", keywords: ["party", "birthday"] },
  { char: "🎁", name: "gift", keywords: ["present", "birthday"] },
  { char: "🏆", name: "trophy", keywords: ["win", "award"] },
  { char: "🥇", name: "first_place", keywords: ["gold", "winner"] },
  { char: "❓", name: "question", keywords: ["help"] },
  { char: "❗", name: "exclamation", keywords: ["warning", "bang"] },
  { char: "✅", name: "white_check_mark", keywords: ["done", "yes", "check"] },
  { char: "☑️", name: "ballot_box_with_check", keywords: ["done", "check"] },
  { char: "✔️", name: "heavy_check_mark", keywords: ["done", "yes"] },
  { char: "❌", name: "x", keywords: ["no", "cross", "wrong"] },
  { char: "⛔", name: "no_entry", keywords: ["stop", "forbidden"] },
  { char: "🚫", name: "no_entry_sign", keywords: ["forbidden", "ban"] },
  { char: "⚠️", name: "warning", keywords: ["caution"] },
  { char: "🆗", name: "ok", keywords: ["okay"] },
  { char: "🆕", name: "new", keywords: [] },

  // Animals & nature
  { char: "🐶", name: "dog", keywords: ["puppy"] },
  { char: "🐱", name: "cat", keywords: ["kitten"] },
  { char: "🦊", name: "fox", keywords: [] },
  { char: "🐻", name: "bear", keywords: [] },
  { char: "🐼", name: "panda", keywords: [] },
  { char: "🐨", name: "koala", keywords: [] },
  { char: "🦁", name: "lion", keywords: [] },
  { char: "🐯", name: "tiger", keywords: [] },
  { char: "🐷", name: "pig", keywords: [] },
  { char: "🐸", name: "frog", keywords: [] },
  { char: "🐵", name: "monkey_face", keywords: [] },
  { char: "🙈", name: "see_no_evil", keywords: ["monkey"] },
  { char: "🐔", name: "chicken", keywords: [] },
  { char: "🐧", name: "penguin", keywords: [] },
  { char: "🐦", name: "bird", keywords: [] },
  { char: "🦄", name: "unicorn", keywords: ["magic"] },
  { char: "🐝", name: "bee", keywords: ["honey"] },
  { char: "🦋", name: "butterfly", keywords: [] },
  { char: "🐢", name: "turtle", keywords: ["slow"] },
  { char: "🐍", name: "snake", keywords: [] },
  { char: "🐙", name: "octopus", keywords: [] },
  { char: "🐳", name: "whale", keywords: [] },
  { char: "🐬", name: "dolphin", keywords: [] },
  { char: "🦈", name: "shark", keywords: [] },
  { char: "🌸", name: "cherry_blossom", keywords: ["flower", "spring"] },
  { char: "🌹", name: "rose", keywords: ["flower"] },
  { char: "🌻", name: "sunflower", keywords: ["flower"] },
  { char: "🌷", name: "tulip", keywords: ["flower"] },
  { char: "🌴", name: "palm_tree", keywords: ["beach"] },
  { char: "🌵", name: "cactus", keywords: [] },
  { char: "🍀", name: "four_leaf_clover", keywords: ["luck"] },
  { char: "🌈", name: "rainbow", keywords: ["pride"] },
  { char: "☀️", name: "sunny", keywords: ["sun", "weather"] },
  { char: "🌙", name: "crescent_moon", keywords: ["night"] },
  { char: "⛅", name: "partly_sunny", keywords: ["cloud", "weather"] },
  { char: "☁️", name: "cloud", keywords: ["weather"] },
  { char: "🌧️", name: "rain_cloud", keywords: ["weather", "rain"] },
  { char: "❄️", name: "snowflake", keywords: ["cold", "winter"] },
  { char: "⛄", name: "snowman", keywords: ["winter"] },
  { char: "🌊", name: "ocean", keywords: ["wave", "water"] },

  // Food & drink
  { char: "🍎", name: "apple", keywords: ["fruit"] },
  { char: "🍌", name: "banana", keywords: ["fruit"] },
  { char: "🍓", name: "strawberry", keywords: ["fruit"] },
  { char: "🍉", name: "watermelon", keywords: ["fruit"] },
  { char: "🍑", name: "peach", keywords: ["fruit", "butt"] },
  { char: "🍒", name: "cherries", keywords: ["fruit"] },
  { char: "🍕", name: "pizza", keywords: ["food"] },
  { char: "🍔", name: "hamburger", keywords: ["food", "burger"] },
  { char: "🍟", name: "fries", keywords: ["food"] },
  { char: "🌮", name: "taco", keywords: ["food"] },
  { char: "🍣", name: "sushi", keywords: ["food"] },
  { char: "🍜", name: "ramen", keywords: ["food", "noodles"] },
  { char: "🍩", name: "doughnut", keywords: ["donut", "food"] },
  { char: "🍪", name: "cookie", keywords: ["food"] },
  { char: "🎂", name: "birthday", keywords: ["cake", "party"] },
  { char: "🍰", name: "cake", keywords: ["dessert"] },
  { char: "🍫", name: "chocolate_bar", keywords: ["candy"] },
  { char: "🍿", name: "popcorn", keywords: ["movie"] },
  { char: "☕", name: "coffee", keywords: ["tea", "drink"] },
  { char: "🍺", name: "beer", keywords: ["drink"] },
  { char: "🍻", name: "beers", keywords: ["cheers", "drink"] },
  { char: "🥂", name: "champagne_glasses", keywords: ["cheers", "toast"] },
  { char: "🍷", name: "wine_glass", keywords: ["drink"] },
  { char: "🍾", name: "champagne", keywords: ["celebrate", "bottle"] },

  // Activities, travel & objects
  { char: "⚽", name: "soccer", keywords: ["football", "sport"] },
  { char: "🏀", name: "basketball", keywords: ["sport"] },
  { char: "🏈", name: "football", keywords: ["sport"] },
  { char: "⚾", name: "baseball", keywords: ["sport"] },
  { char: "🎾", name: "tennis", keywords: ["sport"] },
  { char: "🎮", name: "video_game", keywords: ["gaming", "controller"] },
  { char: "🎲", name: "game_die", keywords: ["dice"] },
  { char: "🎯", name: "dart", keywords: ["target", "bullseye"] },
  { char: "🎸", name: "guitar", keywords: ["music"] },
  { char: "🎵", name: "musical_note", keywords: ["music"] },
  { char: "🎤", name: "microphone", keywords: ["sing", "karaoke"] },
  { char: "🎧", name: "headphones", keywords: ["music"] },
  { char: "🚗", name: "car", keywords: ["drive"] },
  { char: "✈️", name: "airplane", keywords: ["travel", "flight"] },
  { char: "🚀", name: "rocket", keywords: ["space", "launch", "fast"] },
  { char: "🏠", name: "house", keywords: ["home"] },
  { char: "💻", name: "computer", keywords: ["laptop", "work"] },
  { char: "📱", name: "iphone", keywords: ["phone", "mobile"] },
  { char: "💡", name: "bulb", keywords: ["idea", "light"] },
  { char: "🔑", name: "key", keywords: [] },
  { char: "🔒", name: "lock", keywords: ["secure"] },
  { char: "📷", name: "camera", keywords: ["photo"] },
  { char: "💰", name: "moneybag", keywords: ["money", "cash"] },
  { char: "💵", name: "dollar", keywords: ["money", "cash"] },
  { char: "💎", name: "gem", keywords: ["diamond", "jewel"] },
  { char: "⏰", name: "alarm_clock", keywords: ["time"] },
  { char: "📌", name: "pushpin", keywords: ["pin"] },
  { char: "📎", name: "paperclip", keywords: ["attach"] },
  { char: "✏️", name: "pencil2", keywords: ["write", "edit"] },
  { char: "📝", name: "memo", keywords: ["note", "write"] },
  { char: "🔔", name: "bell", keywords: ["notification"] },
  { char: "🎶", name: "notes", keywords: ["music"] },
  { char: "👀", name: "eyes", keywords: ["look", "see", "watching"] },
  { char: "🧠", name: "brain", keywords: ["smart", "think"] },
];

const norm = (s: string) => s.toLowerCase();

/**
 * Rank emoji by how well their shortcode / keywords match `query`.
 * Exact name match > name prefix > keyword prefix > substring.
 */
export function searchEmojis(query: string, limit = 8): Emoji[] {
  const q = norm(query);
  if (!q) return [];

  const scored: Array<{ e: Emoji; score: number }> = [];
  for (const e of EMOJIS) {
    let score = Infinity;
    if (e.name === q) score = 0;
    else if (e.name.startsWith(q)) score = 1;
    else if (e.keywords?.some((k) => k === q)) score = 2;
    else if (e.keywords?.some((k) => k.startsWith(q))) score = 3;
    else if (e.name.includes(q)) score = 4;
    else if (e.keywords?.some((k) => k.includes(q))) score = 5;
    if (score !== Infinity) scored.push({ e, score });
  }

  scored.sort((a, b) => a.score - b.score || a.e.name.length - b.e.name.length);
  return scored.slice(0, limit).map((s) => s.e);
}

/** Find a single emoji by exact shortcode/alias — used for `:name:` auto-replace. */
export function findEmojiByName(name: string): Emoji | undefined {
  const q = norm(name);
  return EMOJIS.find((e) => e.name === q || e.keywords?.includes(q));
}
